apiVersion: cnap.comcast.net/v1
kind: WebService
metadata:
  name: bnoc-backend
  namespace: your-namespace
spec:
  image: hub.comcast.net/your-team/bnoc-backend:latest
  ports:
    - containerPort: 5000
  livenessProbe:
    httpGet:
      path: /
      port: 5000
    initialDelaySeconds: 30
    periodSeconds: 10
  startupProbe:
    httpGet:
      path: /
      port: 5000
    initialDelaySeconds: 60
    periodSeconds: 10
  env:
    - name: SAT_URL
      value: "https://sat-prod.codebig2.net/v2/oauth/token"
    - name: INCIDENT_API_URL
      value: "https://reactor-iop-api-prod.codebig2.net/api/v1/incident-tickets"
    - name: SAT_SCOPE
      value: "iop-infra:incident-read"
    - name: SAT_CLIENT_ID
      value: "ama_bnociopincidentautomation_production"
    - name: SAT_CLIENT_SECRET
      value: "3e556f8a7525895b282d98ae942da57d"
    - name: ALLOWED_USERS
      value: "VishnuVardhan_Pasupuleti@comcast.com,gest_bnoc@comcast.com,BalaBhargavaLakshmi_Singamaneni@comcast.com,Srihari_C@comcast.com"
    - name: TEAM_PASSWORD
      value: "Relay@2026"
    - name: JWT_SECRET
      value: "super_secure_internal_secret_key"
    - name: GROQ_API_KEY
      value: "${GROQ_API_KEY}"